-- SAMAM AI Supabase schema + seed
-- Generated from the existing SAMAM scholarship dataset.
-- Existing scheme facts are marked needs_verification; verify against official portals before relying on them.

create extension if not exists pgcrypto;

create table if not exists public.scholarships (
  id text primary key,
  name text not null,
  name_ta text,
  category jsonb not null default '[]'::jsonb,
  gender text not null default 'all',
  income_limit numeric not null default 0,
  education_level text,
  provider text,
  benefits text,
  benefits_ta text,
  eligibility jsonb not null default '[]'::jsonb,
  apply_link text,
  tags jsonb not null default '[]'::jsonb,
  source text,
  verification_status text not null default 'needs_verification',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.knowledge_documents (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  source_file text,
  source_type text not null default 'uploaded_document',
  language text not null default 'en',
  content text not null,
  verification_status text not null default 'source_document',
  created_at timestamptz not null default now()
);

create table if not exists public.faqs (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  question_ta text,
  answer text not null,
  answer_ta text,
  source text,
  verification_status text not null default 'needs_verification',
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  scholarship_id text references public.scholarships(id) on delete cascade,
  document_name text not null,
  required boolean not null default true,
  notes text
);

create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  scholarship_id text references public.scholarships(id),
  application_reference text,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.scholarships enable row level security;
alter table public.knowledge_documents enable row level security;
alter table public.faqs enable row level security;
alter table public.documents enable row level security;
alter table public.applications enable row level security;

drop policy if exists "Public can read scholarships" on public.scholarships;
create policy "Public can read scholarships" on public.scholarships for select using (true);

drop policy if exists "Public can read knowledge" on public.knowledge_documents;
create policy "Public can read knowledge" on public.knowledge_documents for select using (true);

drop policy if exists "Public can read faqs" on public.faqs;
create policy "Public can read faqs" on public.faqs for select using (true);

drop policy if exists "Public can read documents" on public.documents;
create policy "Public can read documents" on public.documents for select using (true);

insert into public.scholarships
(id,name,name_ta,category,gender,income_limit,education_level,provider,benefits,benefits_ta,eligibility,apply_link,tags,source,verification_status)
values
('1','Post Matric Scholarship for SC/ST/OBC Students','பி.எம்.எஸ் பட்டதாரி உதவித்தொகை (SC/ST/OBC)','["SC","ST","OBC"]'::jsonb,'all',250000,'post-matric','Government of Tamil Nadu','Full tuition fee + maintenance allowance up to ₹7,500/month','முழு கட்டணம் + பராமரிப்பு கொடுப்புதி மாதம் ₹7,500 வரை','["SC/ST/OBC category","Family income below ₹2.5 lakh/year","Studying post-matriculation (11th, 12th, UG, PG)"]'::jsonb,'https://scholarships.gov.in','["tamil-nadu","post-matric","sc","st","obc"]'::jsonb,'existing_samam_dataset','needs_verification'),
('2','Pre Matric Scholarship for SC/ST Students','முன் பட்டதாரி உதவித்தொகை (SC/ST)','["SC","ST"]'::jsonb,'all',200000,'pre-matric','Government of Tamil Nadu','Stipend up to ₹500/month + book grant ₹1,000/year','மாதம் ₹500 வரை உதவித்தொகை + புத்தக உதவி ₹1,000/ஆண்டு','["SC/ST category","Family income below ₹2 lakh/year","Studying class 1–10"]'::jsonb,'https://scholarships.gov.in','["tamil-nadu","pre-matric","sc","st"]'::jsonb,'existing_samam_dataset','needs_verification'),
('3','National Overseas Scholarship for SC/ST','தேசிய வெளிநாட்டு உதவித்தொகை (SC/ST)','["SC","ST"]'::jsonb,'all',600000,'postgraduate','Government of India','Up to ₹20 lakh/year for tuition + living allowance abroad','ஆண்டு ₹20 லட்சம் வரை கட்டணம் + வெளிநாட்டு வாழ்வாதார உதவி','["SC/ST category","Income below ₹6 lakh/year","Below 35 years age","Admission in foreign university"]'::jsonb,'https://scholarships.gov.in','["overseas","sc","st","postgraduate"]'::jsonb,'existing_samam_dataset','needs_verification'),
('4','Chief Minister''s Merit Scholarship','முதல்வரின் சிறப்பு உதவித்தொகை','["OC","BC","MBC","SC","ST"]'::jsonb,'all',500000,'post-matric','Government of Tamil Nadu','₹5,000 to ₹15,000/year based on merit and level','ஆண்டு ₹5,000 முதல் ₹15,000 வரை தகுதியின் அடிப்படையில்','["Top scorers in board exams","Income below ₹5 lakh/year","Tamil Nadu domicile"]'::jsonb,'https://myscheme.gov.in','["tamil-nadu","merit","all-categories"]'::jsonb,'existing_samam_dataset','needs_verification'),
('5','BC/MBC Scholarship','பி.சி/எம்.பி.சி உதவித்தொகை','["BC","MBC"]'::jsonb,'all',250000,'post-matric','Government of Tamil Nadu','Tuition fee reimbursement + maintenance up to ₹5,000/month','கட்டண திரும்பப் பெறுதல் + பராமரிப்பு மாதம் ₹5,000 வரை','["BC/MBC category","Income below ₹2.5 lakh/year","Post-matric studies"]'::jsonb,'https://scholarships.gov.in','["tamil-nadu","bc","mbc","post-matric"]'::jsonb,'existing_samam_dataset','needs_verification'),
('6','Indira Gandhi Single Girl Child Scholarship','இந்திரா காந்தி ஒரே பெண் குழந்தை உதவித்தொகை','["OC","BC","MBC","SC","ST"]'::jsonb,'female',600000,'post-matric','CBSE / Government of India','₹500/month for 2 years (11th–12th) + tuition support','மாதம் ₹500 (11–12 வகுப்பு) + கட்டண உதவி','["Single girl child in family","Studying 11th–12th in CBSE/State board","Income below ₹6 lakh/year"]'::jsonb,'https://scholarships.gov.in','["girl-child","all-categories","pre-matric"]'::jsonb,'existing_samam_dataset','needs_verification'),
('7','Tamil Nadu Higher Education Special Assistance Scheme','தமிழ்நாடு உயர்கல்வி சிறப்பு உதவித்திட்டம்','["OC","BC","MBC","SC","ST"]'::jsonb,'all',450000,'undergraduate','Government of Tamil Nadu','₹1,000/month for UG + ₹2,000/month for PG students','இளநிலை மாதம் ₹1,000 + முதுநிலை மாதம் ₹2,000','["Tamil Nadu domicile","Income below ₹4.5 lakh/year","Enrolled in UG/PG in TN govt/aided colleges"]'::jsonb,'https://myscheme.gov.in','["tamil-nadu","undergraduate","postgraduate","all-categories"]'::jsonb,'existing_samam_dataset','needs_verification'),
('8','AICTE Pragati Scholarship for Girls','ஏ.ஐ.சி.டி.இ பிரகதி பெண்கள் உதவித்தொகை','["OC","BC","MBC","SC","ST"]'::jsonb,'female',800000,'undergraduate','AICTE','₹50,000/year for technical diploma/degree','ஆண்டு ₹50,000 தொழில்நுட்ப பட்டயம்/படிப்பிற்கு','["Girl student","1st year diploma/degree in AICTE-approved institute","Income below ₹8 lakh/year"]'::jsonb,'https://scholarships.gov.in','["aicte","girls","technical","undergraduate"]'::jsonb,'existing_samam_dataset','needs_verification'),
('9','AICTE Saksham Scholarship for Differently-Abled','ஏ.ஐ.சி.டி.இ சக்ஷம் மாற்றுத்திறனாளிகள் உதவித்தொகை','["OC","BC","MBC","SC","ST"]'::jsonb,'all',800000,'undergraduate','AICTE','₹50,000/year for technical education','ஆண்டு ₹50,000 தொழில்நுட்ப கல்விக்கு','["40% or more disability","1st year diploma/degree in AICTE institute","Income below ₹8 lakh/year"]'::jsonb,'https://scholarships.gov.in','["aicte","disability","technical"]'::jsonb,'existing_samam_dataset','needs_verification'),
('10','National Means-cum-Merit Scholarship (NMMS)','தேசிய வாய்ப்பு-சிறப்பு உதவித்தொகை (என்.எம்.எம்.எஸ்)','["OC","BC","MBC","SC","ST"]'::jsonb,'all',150000,'pre-matric','Government of India','₹12,000/year for 4 years (class 9–12)','ஆண்டு ₹12,000, 4 ஆண்டுகள் (9–12 வகுப்பு)','["Class 8 student","Income below ₹1.5 lakh/year","Qualify NMMS exam"]'::jsonb,'https://scholarships.gov.in','["pre-matric","merit","all-categories"]'::jsonb,'existing_samam_dataset','needs_verification'),
('11','Tamil Nadu First Graduate Concession','முதல் பட்டதாரி மாணவர் கட்டண விலக்கு','["OC","BC","MBC","SC","ST"]'::jsonb,'all',0,'undergraduate','Government of Tamil Nadu','Free tuition for first graduate in family in govt/aided engineering colleges','குடும்பத்தில் முதல் பட்டதாரிக்கு அரசு/உதவி பொறியியல் கல்லூரிகளில் இலவச கட்டணம்','["First graduate in family","Tamil Nadu domicile","Admitted via TNEA counselling"]'::jsonb,'https://tneaonline.org','["tamil-nadu","first-graduate","engineering","all-categories"]'::jsonb,'existing_samam_dataset','needs_verification'),
('12','SC/ST Special Scholarship for Higher Studies','எஸ்.சி/எஸ்.டி உயர்கல்வி சிறப்பு உதவித்தொகை','["SC","ST"]'::jsonb,'all',500000,'postgraduate','Government of Tamil Nadu','Full tuition + ₹5,000/month maintenance for PG studies','முழு கட்டணம் + மாதம் ₹5,000 பராமரிப்பு முதுநிலை படிப்பிற்கு','["SC/ST category","Income below ₹5 lakh/year","PG admission in recognized institute"]'::jsonb,'https://scholarships.gov.in','["sc","st","postgraduate","tamil-nadu"]'::jsonb,'existing_samam_dataset','needs_verification'),
('13','Begum Hazrat Mahal National Scholarship for Girls','பேகம் ஹஸ்ரத் மஹால் தேசிய பெண்கள் உதவித்தொகை','["OC","BC","MBC","SC","ST"]'::jsonb,'female',200000,'pre-matric','Maulana Azad Education Foundation','₹5,000 for class 9–10, ₹6,000 for class 11–12','9–10 வகுப்பிற்கு ₹5,000, 11–12 வகுப்பிற்கு ₹6,000','["Minority girl student","Income below ₹2 lakh/year","Class 9–12"]'::jsonb,'https://scholarships.gov.in','["minority","girls","pre-matric"]'::jsonb,'existing_samam_dataset','needs_verification'),
('14','Pre-Matric Scholarship for Minorities','சிறுபான்மை மாணவர்கள் முன் பட்டதாரி உதவித்தொகை','["OC","BC","MBC"]'::jsonb,'all',100000,'pre-matric','Government of India','₹1,000–₹10,700/year based on class level','வகுப்பின் அடிப்படையில் ஆண்டு ₹1,000–₹10,700','["Minority community","Income below ₹1 lakh/year","Class 1–10"]'::jsonb,'https://scholarships.gov.in','["minority","pre-matric"]'::jsonb,'existing_samam_dataset','needs_verification'),
('15','Post-Matric Scholarship for Minorities','சிறுபான்மை மாணவர்கள் பட்டதாரி உதவித்தொகை','["OC","BC","MBC"]'::jsonb,'all',200000,'post-matric','Government of India','Up to ₹20,000/year for tuition + maintenance','கட்டணம் + பராமரிப்பு ஆண்டு ₹20,000 வரை','["Minority community","Income below ₹2 lakh/year","Post-matric studies"]'::jsonb,'https://scholarships.gov.in','["minority","post-matric"]'::jsonb,'existing_samam_dataset','needs_verification'),
('16','Central Sector Scheme of Scholarships for College Students','மத்திய துறை கல்லூரி மாணவர்கள் உதவித்தொகை','["OC","BC","MBC","SC","ST"]'::jsonb,'all',450000,'undergraduate','Government of India','₹1,000/month for UG, ₹2,000/month for PG (up to 10 months/year)','இளநிலை மாதம் ₹1,000, முதுநிலை மாதம் ₹2,000 (ஆண்டு 10 மாதங்கள்)','["80%+ in 12th board","Income below ₹4.5 lakh/year","Regular UG/PG student"]'::jsonb,'https://scholarships.gov.in','["central","undergraduate","postgraduate","merit"]'::jsonb,'existing_samam_dataset','needs_verification'),
('17','Tamil Nadu 7.5% Horizontal Reservation (Govt School Students)','தமிழ்நாடு 7.5% கிடைமட்ட இட ஒதுக்கீடு (அரசு பள்ளி மாணவர்கள்)','["OC","BC","MBC","SC","ST"]'::jsonb,'all',0,'undergraduate','Government of Tamil Nadu','Guaranteed admission in medical/engineering for govt school toppers','அரசு பள்ளி மாணவர்களுக்கு மருத்துவ/பொறியியல் உறுதி சேர்க்கை','["Studied 6–12 in TN govt school","Qualified NEET/TNEA","Applied via counselling"]'::jsonb,'https://tneaonline.org','["tamil-nadu","govt-school","engineering","medical","reservation"]'::jsonb,'existing_samam_dataset','needs_verification'),
('18','INSPIRE Scholarship (Science Students)','இன்ஸ்பயர் உதவித்தொகை (அறிவியல் மாணவர்கள்)','["OC","BC","MBC","SC","ST"]'::jsonb,'all',0,'undergraduate','Department of Science & Technology','₹80,000/year for 5 years (BSc/MSc in natural sciences)','ஆண்டு ₹80,000, 5 ஆண்டுகள் (இயற்பியல் அறிவியல் BSc/MSc)','["Top 1% in 12th board or JEE rank < 10,000","Pursuing BSc/MSc in natural/basic sciences","Age 17–22"]'::jsonb,'https://scholarships.gov.in','["science","inspire","undergraduate","merit"]'::jsonb,'existing_samam_dataset','needs_verification'),
('19','PG Indira Gandhi Scholarship for Single Girl Child','இந்திரா காந்தி முதுநிலை உதவித்தொகை (ஒரே பெண் குழந்தை)','["OC","BC","MBC","SC","ST"]'::jsonb,'female',0,'postgraduate','UGC','₹36,200/year for 2 years of PG','ஆண்டு ₹36,200, 2 ஆண்டுகள் முதுநிலை படிப்பிற்கு','["Single girl child","Admitted to PG course","Age below 30"]'::jsonb,'https://scholarships.gov.in','["ugc","girls","postgraduate","single-girl"]'::jsonb,'existing_samam_dataset','needs_verification'),
('20','Tamil Nadu Adi Dravidar Welfare Scholarship','தமிழ்நாடு அடிதிராவிடர் நல உதவித்தொகை','["SC"]'::jsonb,'all',200000,'pre-matric','Government of Tamil Nadu','Free education + ₹500/month + books + uniform','இலவச கல்வி + மாதம் ₹500 + புத்தகம் + சீருடை','["SC category","Income below ₹2 lakh/year","Class 1–12 in TN"]'::jsonb,'https://scholarships.gov.in','["tamil-nadu","sc","pre-matric","adi-dravidar"]'::jsonb,'existing_samam_dataset','needs_verification'),
('21','Tamil Nadu Tribal Welfare Scholarship','தமிழ்நாடு பழங்குடி நல உதவித்தொகை','["ST"]'::jsonb,'all',200000,'pre-matric','Government of Tamil Nadu','Free education + boarding + books + ₹600/month','இலவச கல்வி + வசதி + புத்தகம் + மாதம் ₹600','["ST category","Income below ₹2 lakh/year","Class 1–12 in TN"]'::jsonb,'https://scholarships.gov.in','["tamil-nadu","st","pre-matric","tribal"]'::jsonb,'existing_samam_dataset','needs_verification'),
('22','Ishan Uday Scholarship for North East Students','ஈஷான் உதய் வடகிழக்கு மாணவர்கள் உதவித்தொகை','["OC","BC","MBC","SC","ST"]'::jsonb,'all',450000,'undergraduate','UGC','₹5,400/month (UG general), ₹7,800/month (PG/technical)','இளநிலை மாதம் ₹5,400, முதுநிலை/தொழில்நுட்ப மாதம் ₹7,800','["Domicile of North East states","Income below ₹4.5 lakh/year","1st year UG/PG"]'::jsonb,'https://scholarships.gov.in','["north-east","ugc","undergraduate"]'::jsonb,'existing_samam_dataset','needs_verification'),
('23','Post-Matric Scholarship for OBC Students (Central)','பி.எம்.எஸ் பிற பிற்படு வகுப்பினர் உதவித்தொகை (மத்திய)','["BC","OBC"]'::jsonb,'all',150000,'post-matric','Government of India','Tuition + maintenance up to ₹7,500/month','கட்டணம் + பராமரிப்பு மாதம் ₹7,500 வரை','["OBC category","Income below ₹1.5 lakh/year","Post-matric studies"]'::jsonb,'https://scholarships.gov.in','["obc","central","post-matric"]'::jsonb,'existing_samam_dataset','needs_verification'),
('24','PG Scholarship for Professional Courses (SC/ST)','தொழில்முறை முதுநிலை உதவித்தொகை (SC/ST)','["SC","ST"]'::jsonb,'all',600000,'postgraduate','Government of India','₹3,000/month (ME/MTech) or ₹4,500/month (MPhil/PhD)','மாதம் ₹3,000 (ME/MTech) அல்லது ₹4,500 (MPhil/PhD)','["SC/ST category","Income below ₹6 lakh/year","PG in professional courses"]'::jsonb,'https://scholarships.gov.in','["sc","st","postgraduate","professional"]'::jsonb,'existing_samam_dataset','needs_verification'),
('25','Swami Vivekananda Merit-cum-Means Scholarship','சுவாமி விவேகானந்தர் தகுதி-வருமான உதவித்தொகை','["OC","BC","MBC","SC","ST"]'::jsonb,'all',250000,'post-matric','Government of Tamil Nadu','₹1,500–₹5,000/month based on education level','கல்வி நிலையின் அடிப்படையில் மாதம் ₹1,500–₹5,000','["Merit in last exam (60%+)","Income below ₹2.5 lakh/year","Class 11 to PG"]'::jsonb,'https://myscheme.gov.in','["tamil-nadu","merit","all-categories","post-matric"]'::jsonb,'existing_samam_dataset','needs_verification'),
('26','Tamil Nadu Free Education for Girls (Beti Bachao)','தமிழ்நாடு பெண்கள் இலவச கல்வி (பேட்டி பசாவ்)','["OC","BC","MBC","SC","ST"]'::jsonb,'female',300000,'pre-matric','Government of Tamil Nadu','Free education up to degree + ₹1,500/year for books','பட்டம் வரை இலவச கல்வி + ஆண்டு ₹1,500 புத்தக உதவி','["Girl student","Income below ₹3 lakh/year","Class 1 to UG in TN"]'::jsonb,'https://myscheme.gov.in','["tamil-nadu","girls","pre-matric","beti-bachao"]'::jsonb,'existing_samam_dataset','needs_verification'),
('27','Kanya Sumangala Yojana (UP-origin TN students)','கன்யா சுமங்கலா திட்டம்','["OC","BC","MBC","SC","ST"]'::jsonb,'female',300000,'pre-matric','Government of Uttar Pradesh','Total ₹25,000 in installments from birth to UG','பிறப்பு முதல் இளநிலை வரை மொத்தம் ₹25,000 தவணைகளில்','["Girl child","UP domicile (transferable)","Income below ₹3 lakh/year"]'::jsonb,'https://myscheme.gov.in','["girls","pre-matric","kanya-sumangala"]'::jsonb,'existing_samam_dataset','needs_verification'),
('28','Tamil Nadu Backward Classes Economic Support','தமிழ்நாடு பிற பிற்படு வகுப்பினர் பொருளாதார உதவி','["BC","MBC"]'::jsonb,'all',300000,'undergraduate','Government of Tamil Nadu','₹8,000/year for UG + exam fee reimbursement','இளநிலை ஆண்டு ₹8,000 + தேர்வு கட்டண திரும்பப் பெறுதல்','["BC/MBC category","Income below ₹3 lakh/year","UG in TN govt/aided college"]'::jsonb,'https://myscheme.gov.in','["tamil-nadu","bc","mbc","undergraduate"]'::jsonb,'existing_samam_dataset','needs_verification'),
('29','Dr. Ambedkar Scholarship for DNT Students','டாக்டர் அம்பேத்கர் டி.என்.டி மாணவர்கள் உதவித்தொகை','["OC"]'::jsonb,'all',200000,'post-matric','Government of India','Tuition + maintenance up to ₹5,000/month','கட்டணம் + பராமரிப்பு மாதம் ₹5,000 வரை','["Denotified tribe (DNT)","Income below ₹2 lakh/year","Post-matric studies"]'::jsonb,'https://scholarships.gov.in','["dnt","post-matric","ambedkar"]'::jsonb,'existing_samam_dataset','needs_verification'),
('30','Tamil Nadu Free Laptop Scheme for Students','தமிழ்நாடு இலவச மடிக்கணினி திட்டம்','["OC","BC","MBC","SC","ST"]'::jsonb,'all',0,'post-matric','Government of Tamil Nadu','Free laptop for +2 students in govt/aided schools','அரசு/உதவி பள்ளி +2 மாணவர்களுக்கு இலவச மடிக்கணினி','["Studying +2 in TN govt/aided school","All categories","Tamil Nadu domicile"]'::jsonb,'https://myscheme.gov.in','["tamil-nadu","laptop","all-categories","post-matric"]'::jsonb,'existing_samam_dataset','needs_verification'),
('31','Tamil Nadu Higher Education Assurance Scheme','தமிழ்நாடு உயர்கல்வி உறுதி திட்டம்','["OC","BC","MBC","SC","ST"]'::jsonb,'all',600000,'undergraduate','Government of Tamil Nadu','₹15,000/year + bus pass for college students','ஆண்டு ₹15,000 + கல்லூரி மாணவர் பேருந்து பாஸ்','["Tamil Nadu domicile","Income below ₹6 lakh/year","UG in TN govt/aided colleges"]'::jsonb,'https://myscheme.gov.in','["tamil-nadu","undergraduate","all-categories"]'::jsonb,'existing_samam_dataset','needs_verification')
on conflict (id) do update set
name=excluded.name,name_ta=excluded.name_ta,category=excluded.category,gender=excluded.gender,
income_limit=excluded.income_limit,education_level=excluded.education_level,provider=excluded.provider,
benefits=excluded.benefits,benefits_ta=excluded.benefits_ta,eligibility=excluded.eligibility,
apply_link=excluded.apply_link,tags=excluded.tags,source=excluded.source,
verification_status=excluded.verification_status,updated_at=now();

insert into public.knowledge_documents (title, source_file, source_type, language, content, verification_status)
select 'BC/MBC Scholarship Guidelines', 'BC MBC - Fresh form.pdf', 'uploaded_document', 'en',
'This uploaded guideline states that regular students who meet the scholarship eligibility criteria can apply for private and government/welfare scholarships, subject to the respective scholarship conditions. It also lists government quota students as eligible to apply for community scholarships including FG, BC, DNC, SC and PMSS, while management quota eligibility differs. Existing scholarship or financial assistance must be disclosed and combination rules must be checked.',
'source_document'
where not exists (
  select 1 from public.knowledge_documents where title='BC/MBC Scholarship Guidelines'
);

insert into public.knowledge_documents (title, source_file, source_type, language, content, verification_status)
select 'BC/MBC Scholarship Notes', 'Scholarship Application Guidelines tc.pdf', 'uploaded_document', 'en',
'The uploaded scholarship guideline says active scholarship opportunities are shared periodically as concerned agencies release official scholarship announcements. It also says government schemes in the NSP portal are subject to the stated one-scholarship application condition in the document.',
'source_document'
where not exists (
  select 1 from public.knowledge_documents where title='BC/MBC Scholarship Notes'
);


-- Scholarship Guide 2026–27 supplied by the user (prepared/checked 30 Sep 2026).
-- This is kept separate from the older demo scholarship dataset so the app can
-- distinguish the new source-backed guide from legacy demo records.
create table if not exists public.scholarship_guide_2026_27 (
  id text primary key,
  name text not null,
  type text not null check (type in ('government','private')),
  eligibility text not null,
  benefits text not null,
  documents text not null,
  application_route text not null,
  official_source text not null,
  status_notes text,
  source_file text not null default 'scholarship_guide_2026_27.pdf',
  prepared_date date not null default '2026-09-30',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.scholarship_guide_2026_27 enable row level security;
drop policy if exists "Public can read 2026-27 guide" on public.scholarship_guide_2026_27;
create policy "Public can read 2026-27 guide"
  on public.scholarship_guide_2026_27 for select using (true);

insert into public.scholarship_guide_2026_27
(id,name,type,eligibility,benefits,documents,application_route,official_source,status_notes)
values
('g01','PM-USP Central Sector Scholarship (CSSS)','government','Indian students above the 80th percentile in Class XII entering a regular UG course; family income generally <= ₹4.5 lakh/year; scheme conditions exclude diploma/drop-after-12th cases.','₹12,000/year for UG years 1–3; ₹20,000/year for later eligible years/PG as per scheme; DBT.','Class XII marksheet, income certificate, Aadhaar/OTR, bank account, admission/institution details; category/disability documents if applicable.','Create/possess NSP OTR → select CSSS → fill → upload/verify → institute verification → further verification → DBT.','https://scholarships.gov.in/ | https://www.education.gov.in/','2026–27 NSP scheme family is listed; exact student deadline must be checked in Specifications/FAQ.'),
('g02','PM YASASVI – Top Class Education in College (OBC/EBC/DNT)','government','OBC/EBC/DNT students in a full-time course in a Ministry-notified Top Class institution; family income <= ₹2.5 lakh/year; institution/course slots and merit apply.','Full tuition/non-refundable charges subject to ceilings; living ₹3,000/month; books ₹5,000/year; one-time computer/accessories support up to ₹45,000.','Caste/category certificate, income certificate, Class XII/qualifying marksheet, admission proof, fee details, bank/Aadhaar/OTR; sibling affidavit where required.','Apply through NSP; institution verifies. Tamil Nadu BC/MBC/DNC students should also check the separate TN post-matric UMIS route.','https://scholarships.gov.in/ | https://socialjustice.gov.in/','Check current Specifications/FAQ for exact dates.'),
('g03','AICTE Pragati Scholarship – Girl Students','government','Girl student in 1st-year degree or 2nd-year lateral-entry degree in an AICTE-approved institution; family income <= ₹8 lakh/year; maximum two girl children per family; merit-based.','₹50,000/year for the eligible study period, subject to scheme rules; DBT.','Income certificate, qualifying marksheet, admission/institute details, Aadhaar/OTR, bank details and other requested records.','Apply online through NSP when the AICTE cycle is open; institute and state technical-education authorities verify.','https://scholarships.gov.in/ | https://www.aicte-india.org/','Exact deadline must be checked on NSP.'),
('g04','AICTE Swanath Scholarship','government','Eligible technical students who are orphans, whose parent(s) died due to COVID-19, or wards of Armed Forces/Central Paramilitary personnel martyred in action; regular AICTE-approved degree/diploma; family income <= ₹8 lakh/year.','₹50,000/year for eligible degree students, subject to scheme duration and conditions; DBT.','Qualifying-category proof, income certificate, marksheet, admission proof, Aadhaar/OTR and bank details.','NSP → Swanath → upload proof → institute/state verification → DBT.','https://scholarships.gov.in/ | https://www.aicte-india.org/','Exact deadline must be checked on NSP.'),
('g05','AICTE Saksham Scholarship – Specially-Abled Students','government','Student with disability of at least 40%, in 1st-year or lateral-entry technical degree/diploma in an AICTE-approved institution; family income <= ₹8 lakh/year.','₹50,000/year for eligible study period, subject to scheme duration; DBT.','Disability certificate/UDID, income certificate, qualifying marksheet, admission proof, Aadhaar/OTR, bank details.','Apply through NSP; disabled applicants must complete the required UDID consent step before NSP submission.','https://scholarships.gov.in/ | https://depwd.gov.in/','Check live NSP notice before submission.'),
('g06','Post-Matric Scholarship for Students with Disabilities','government','Students with benchmark disability (generally 40% or more, certified by competent authority) studying post-matric/post-secondary courses; published scheme income ceiling generally ₹2.5 lakh/year.','Scholarship/fee reimbursement plus maintenance and other allowances subject to course/group ceilings.','UDID/disability certificate, income certificate, marksheet, admission/bonafide, fee details, bank/Aadhaar/OTR, photo.','NSP → UDID consent/OTR → upload → institute/state verification → DBT/reimbursement as applicable.','https://scholarships.gov.in/ | https://www.myscheme.gov.in/hi/schemes/post-dis','Exact scheme ceilings and dates should be verified live.'),
('g07','Top Class Education for Students with Disabilities','government','Students with specified benchmark disability admitted to eligible higher-education institutions; income ceiling and other DEPwD conditions apply.','Tuition/non-refundable fee support up to prescribed ceiling; maintenance, special allowance, books/stationery and one-time computer/assistive-device support under scheme rules.','UDID/disability certificate, income certificate, admission proof, fee receipt, previous marks, bank/Aadhaar/OTR, institution details.','Apply through NSP after UDID consent/verification; institution and nodal authorities verify.','https://scholarships.gov.in/ | https://depwd.gov.in/','Check current DEPwD/NSP rules.'),
('g08','Top Class Education for SC Students','government','SC students beyond Class XII in Ministry-notified institutions; institution/course and slot conditions apply.','Full tuition/non-refundable charges within scheme ceilings; living expenses, books/stationery and one-time computer support.','SC certificate, income certificate, admission proof, qualifying marksheet, fee details, bank/Aadhaar/OTR, institution documents.','Apply through NSP; institution and departmental verification follow.','https://scholarships.gov.in/ | https://socialjustice.gov.in/schemes/27','Check current official guidelines for exact ceilings and deadline.'),
('g09','Higher Education Scholarship for ST Students (Top Class)','government','ST students in prescribed courses in Ministry-notified top institutions; parental income generally <= ₹6 lakh/year under the current scheme description.','Tuition plus living expenses, book/stationery and computer/other allowances subject to ceilings.','ST certificate, income certificate, qualifying marksheet, admission proof, fee details, bank/Aadhaar/OTR.','Apply through NSP; institute and Ministry/State verification as applicable.','https://scholarships.gov.in/ | https://tribal.nic.in/','Check current scheme description and deadline.'),
('g10','Beedi/Cine/IOMC/LSDM Workers Welfare – Post-Matric','government','Ward of an eligible Beedi, mine or Cine worker with at least six months service, subject to worker-income/service conditions; student must have passed previous qualifying exam.','For AY 2026–27 published rates: ₹6,000/year for ITI/polytechnic/degree courses and ₹25,000/year for professional courses; DBT.','Worker identity/registration proof, income certificate, previous marksheet, photo, bank passbook/cancelled cheque, Aadhaar/OTR.','NSP → Post-Matric welfare scheme → upload → institute/department verification.','https://scholarships.gov.in/ | https://labour.gov.in/','Check current NSP Specifications/FAQ.'),
('g11','PM Scholarship Scheme – CAPF & Assam Rifles','government','Wards/widows of eligible CAPF/Assam Rifles personnel; merit and course conditions apply for higher technical/professional education.','Published PMSS rate: ₹30,000/year for boys and ₹36,000/year for girls, subject to slots and course rules.','Service/dependency certificate, marksheet, admission proof, bank details, Aadhaar/OTR and CAPF/AR documents.','Apply through NSP during the notified window; institute and department verify.','https://scholarships.gov.in/ | https://mha.gov.in/','Current notification controls exact conditions.'),
('g12','PM Scholarship Scheme – State/UT Police Personnel Martyred in Terror/Naxal Attacks','government','Wards of eligible State/UT police personnel martyred during terror/naxal attacks; merit, course and dependency conditions apply.','PMSS financial assistance for eligible technical/professional higher education; amount follows current PMSS notification.','Martyr/dependency certificate, marksheet, admission proof, bank/Aadhaar/OTR, police department documents.','NSP → upload → institute and departmental verification.','https://scholarships.gov.in/ | https://mha.gov.in/','Verify current PMSS notification.'),
('g13','PM Scholarship Scheme – Ministry of Railways','government','Eligible wards of specified railway personnel/deceased railway personnel; merit and approved-course conditions apply.','PMSS support for eligible higher technical/professional courses; annual amount is governed by Railway Board notification.','Railway employee/dependency certificate, marksheet, admission proof, bank/Aadhaar/OTR and course documents.','Apply through NSP during notified window; institute/Railway verification follows.','https://scholarships.gov.in/ | https://indianrailways.gov.in/','Verify current Railway Board notification.'),
('g14','National Renewable Energy Fellowship Scheme','government','Higher studies/research in renewable energy including M.Sc., M.Tech, PhD and research fellowships under MNRE rules; not a general UG scholarship.','Published MNRE rates include M.Tech/M.S. ₹12,400/month and M.Sc. renewable energy ₹4,000/month; JRF/SRF/RA/PDF rates follow applicable norms.','Admission/research offer, academic records, institute eligibility, identity/bank details and implementing-institute documents.','Apply according to MNRE/implementing-institute notification; NSP may list the scheme.','https://scholarships.gov.in/ | https://mnre.gov.in/en/fellowships-for-higher-studies-and-research-in-renewable-energy/','Research-focused; verify current notification.'),
('g15','NEC Merit Scholarship','government','Permanent resident of a North-Eastern state; recognized diploma/degree/PG/M.Phil./PhD; generally minimum 60% and parental income <= ₹8 lakh/year.','Monthly scholarship varies by level under current NEC guidelines.','Permanent Residential Certificate/COI, marksheet, income certificate, admission proof, bank/Aadhaar/OTR.','Apply through NSP within NEC window; state/NEC verification applies.','https://scholarships.gov.in/ | https://necouncil.gov.in/','For NER residents.'),
('g16','Ishan Uday Special Scholarship Scheme for NER','government','Students domiciled in North-Eastern Region states in eligible first-year regular UG programmes; income and course conditions apply.','UGC scholarship support paid monthly; exact rate depends on current UGC notification.','NER domicile/residential certificate, Class XII marksheet, income certificate, admission proof, bank/Aadhaar/OTR.','Apply via NSP; institute and state/UGC verification.','https://scholarships.gov.in/ | https://www.ugc.gov.in/','For NER residents.'),
('g17','National Scholarship for Post Graduate Studies','government','Indian students admitted to first year of eligible regular/full-time PG degree; age limit 30; integrated programmes supported for PG component.','₹1,50,000/year for 2 years; 10,000 slots/year as stated in the guide.','UG degree/marksheet, PG admission proof, age/identity, bank/Aadhaar/OTR, institution details.','NSP → select NSPG → upload and verify.','https://scholarships.gov.in/ | https://www.ugc.gov.in/Scholarships/stu_Scholarship6','Check current UGC/NSP notice.'),
('g18','ICAR National Talent Scholarship (NTS)','government','UG/PG students admitted through prescribed all-India ICAR route to eligible agriculture/allied programmes outside domicile state; full-time study and performance rules apply.','₹2,000/month for Bachelor’s and ₹3,000/month for Master’s, renewable subject to academic performance.','ICAR admission/allotment proof, domicile proof, marksheet, university certificate, bank/Aadhaar/OTR as required.','Apply through NSP when ICAR cycle is open; institution verifies.','https://scholarships.gov.in/ | https://icar.gov.in/','Check current ICAR cycle.'),
('g19','Tamil Nadu MBC Post-Matric Scholarship','government','Tamil Nadu BC/MBC/DNC students in eligible post-matric courses; 2026–27 has a separate UMIS route; rules vary by course and institution. For many professional/PG/research courses, income ceiling is ₹2.5 lakh/year.','Course-based scholarship/fee support under TN Backward Classes Welfare rules; exact amount depends on course, institution and approved fee.','Community certificate, income certificate where applicable, Aadhaar, bank account, previous marksheet, admission/bonafide, fee details.','Contact college scholarship/nodal officer and apply through UMIS for the notified period.','https://umiss.tn.gov.in/ | https://bcmbcmw.tn.gov.in/','Guide states 2026–27 UMIS window: 18-09-2026 to 21-10-2026 for eligible BC/MBC/DNC students through college nodal officer.'),
('g20','Tamil Nadu BC/MBC/DNC Scholarship Portal (UMIS)','government','TN application portal/route for eligible BC/MBC/DNC welfare schemes according to course, quota, institution and income rules.','Benefit depends on the underlying TN scheme and may include fee support, maintenance/hostel-related assistance or other approved educational support.','Community certificate, income certificate, Aadhaar, bank details, marksheet, bonafide/admission proof and fee details are commonly required.','Login/registration through UMIS as directed by college nodal officer; submit for college verification.','https://umiss.tn.gov.in/ | https://bcmbcmw.tn.gov.in/','UMIS is the route; exact benefit depends on the underlying TN scheme.'),
('p01','Reliance Foundation Undergraduate Scholarship','private','Indian citizen; Class XII >=60%; first-year regular full-time UG in 2026–27; household income <₹15 lakh; aptitude test mandatory.','Up to ₹2 lakh over the degree; merit-cum-means plus alumni/support network.','Class XII marksheet, income proof, admission proof, identity, bank details and supporting documents.','Apply on Reliance Foundation scholarship portal → form → aptitude test → document/merit-cum-means selection.','https://www.scholarships.reliancefoundation.org/UG_Scholarship','Guide says applications are open for first-year UG students.'),
('p02','Kotak Kanya Scholarship','private','Girl student; Class XII >=75%; first-year professional UG in 2026–27; family income <=₹6 lakh.','₹1.5 lakh/year subject to terms for the professional degree; may cover tuition, hostel, laptop, books, transport and academic costs.','Class XII marksheet, income/ITR, fee structure, bonafide/admission/seat document, entrance scorecard, masked Aadhaar, bank passbook, photo.','Online through published Kotak/Buddy4Study route.','https://www.kotakeducationfoundation.org/','Guide states current cycle closes 30 Sep 2026.'),
('p03','Bharti Airtel Scholarship','private','First-year UG engineering/5-year integrated technology at a top-50 NIRF-ranked engineering institution; family income <=₹8 lakh; Indian citizen/resident; exclusivity conditions apply.','100% annual fee coverage under 2026–27 programme, subject to programme rules.','Government ID, Class XII marksheet, JEE/university entrance score, admission/fee proof, parental income documents.','Apply through Bharti Airtel Foundation scholarship page and complete online selection/verification.','https://www.bhartiairtelfoundation.org/bharti-airtel-scholarship','Guide says applications are open.'),
('p04','HDFC Bank Parivartan ECSS','private','Indian national; UG students in recognized general/professional courses; previous exam >=55%; family income <=₹2.5 lakh; preference for recent personal/family crisis.','₹30,000 for general UG or ₹50,000 for professional UG in 2026–27; higher awards apply to PG categories.','Photo, previous marksheet, ID, admission proof, bank details, income proof and crisis proof if applicable.','Apply online via official ECSS/Buddy4Study route; verification/interview may follow.','https://www.parivartanecss.com/','Guide lists 31 Oct 2026 as deadline.'),
('p05','Legrand Empowering Scholarship','private','Eligible girl students and specified special-category students pursuing higher education; course, marks and income conditions apply.','General category: 80% of annual course fee up to ₹80,000/year. Special category: 80% up to ₹1,00,000/year, subject to terms.','Current fee structure/receipt, previous marksheet, bank passbook, declaration and requested identity/income/admission documents.','Apply through programme portal; annual document submission is required for renewal.','https://legrandscholarship.co.in/','Guide states current benefit ceilings.'),
('p06','Panasonic Ratti Chhatr Scholarship','private','First-year B.E./B.Tech at an IIT in 2026–27; Class XII >75%; family income <=₹8 lakh; screening/test/interview.','₹70,250/year for 2026–27 as published in the guide.','Class XII marksheet, IIT admission letter, first-semester fee receipt, income proof, ID, bank details.','Apply online through the current route, implemented with Buddy4Study.','https://www.panasonic.com/in/corporate/news/articles/panasonic-life-solutions-india-marks-10-years-of-ratti-cchhatr-scholarship-program.html','Verify live application deadline.'),
('p07','Infosys Foundation STEM Stars Scholarship','private','Female Indian student in first-year STEM UG at eligible NIRF-accredited institution; family income <=₹8 lakh; programme-specific rules.','Up to ₹1 lakh/year for eligible course duration toward tuition, study materials and living/education costs.','Class XII/previous marksheet, admission proof, income certificate, ID, bank details, fee documents.','Apply through announced Infosys Foundation/Buddy4Study window.','https://www.infosys.com/newsroom/press-releases/2023/launch-stem-scholarship-program.html','Guide says next application window may be announced later; check official page.'),
('p08','KSB Scholarship & Mentorship Program','private','First-year girls in engineering diploma/polytechnic; usually >60% previous study; family income <₹8 lakh; location/domicile restrictions include Coimbatore and specified districts.','Scholarship plus mentorship; current amount should be confirmed in the 2026–27 notice.','Marksheets, income proof, admission/bonafide, ID, bank details and domicile/location proof if requested.','Current provider/Buddy4Study application route.','https://www.ksb.com/','Verify current amount and eligibility notice.'),
('p09','Rolls-Royce Wings4Her Scholarship','private','Female students in eligible engineering/technical education; current listings indicate academic merit and financial-need conditions.','Current 2026 listings in the guide show roughly ₹25,000–₹35,000 support plus mentorship, subject to programme rules.','Marksheets, income proof, admission/bonafide, ID, bank details and course/location proof if requested.','Current programme application route; selection and verification follow.','https://www.rolls-royce.com/','Verify current notice before applying.'),
('p10','Tata Capital Pankh Scholarship','private','Indian students in eligible Class 11/12, UG, diploma/polytechnic/ITI courses; 2026–27 UG/professional rules commonly require >=60% and family income <=₹4 lakh.','For 2026–27, UG/diploma/polytechnic/ITI support up to ₹18,000 or eligible course-fee amount as per programme.','Aadhaar/ID, photo, income proof, admission/bonafide, current fee receipt, bank details, previous marksheet, caste/disability proof if applicable.','Apply online through current programme route.','https://www.tatacapital.com/','Verify current track rules.'),
('p11','SBI Asha Scholarship','private','Multiple 2026–27 tracks; higher-education tracks generally income <=₹6 lakh and minimum 75%/7.0 CGPA, with published relaxation for SC/ST; institution/category rules differ.','Awards vary by track; eligible UG at top-300 NIRF institutions up to ₹75,000/year; other tracks have different ceilings.','Marksheets, income proof, admission proof, ID, bank details and institution documents.','Create account on SBI Foundation Asha portal → choose track → upload → submit.','https://www.sbiashascholarship.co.in/','Track-specific conditions apply.'),
('p12','Aditya Birla Capital Scholarship','private','Specified school, diploma, UG and PG categories; typical UG criteria include >=60% and family income <=₹6 lakh.','Up to ₹45,000 for general graduation and up to ₹60,000 for specified professional/PG categories.','Photo, previous marksheets, ID, admission/bonafide, fee/expense receipts, bank passbook, income proof and supporting certificates if applicable.','Apply online through current Aditya Birla Capital/Buddy4Study route.','https://www.adityabirlacapital.com/','Exact track rules apply.'),
('p13','LIC Golden Jubilee Scholarship','private','Indian students in recognized higher education/technical/vocational courses; current scheme uses merit plus income criteria.','2026 programme has General and Special (girls) categories; amount depends on current LIC notification.','Qualifying marksheet, admission proof, income proof, ID, bank details and requested documents.','Apply through LIC Golden Jubilee Foundation 2026 scholarship page; preliminary and final document evaluation.','https://licindia.in/en/web/guest/golden-jubilee-foundation','Check current scheme document for qualifying-year rules.'),
('p14','K.C. Mahindra Education Trust Scholarship','private','Primarily postgraduate/foreign-study scholarship for Indian students with first-class degree/diploma and admission/application to reputable foreign universities; not a normal first-year Indian UG scholarship.','Interest-free loan scholarship for overseas postgraduate study; amount and cycle conditions notified annually.','Degree/diploma marksheets, admission/application evidence, university documents, references and identity/financial documents.','Annual online application process.','https://www.kcmet.org/','Foreign postgraduate focus.'),
('p15','FFE Scholarship Program','private','Indian citizens; first-year engineering/MBBS/law in 2026–27; engineering applicants must meet FFE entrance-rank criteria; combined family income <=₹4 lakh.','₹50,000/year until graduation, renewable subject to continuation/programme rules.','Class XII marksheet, entrance-rank proof, admission proof, income/financial documents, identity and bank details.','Apply through Foundation for Excellence website; selection considers merit and financial circumstances.','https://ffe.org/ffe-wsp-scholarship-program/','Check current programme notice.'),
('p16','Santoor Women’s Scholarship Program','private','Girl students from specified states/backgrounds entering eligible UG programmes; state, school and course conditions apply.','2026 listings show ₹30,000/year; duration and eligible expenses depend on current programme rules.','Class X/XII marksheets, admission proof, income/residential documents, ID and bank details.','Current Santoor/Wipro scholarship application route.','https://www.wipro.com/','Check current cycle.'),
('p17','JK Tyre Shiksha Sarthi Scholarship','private','Female students who are daughters of heavy-vehicle drivers in eligible UG/diploma courses; guide listing: >=55%, family income <=₹5 lakh; Tamil Nadu included among eligible states.','Up to ₹25,000/year for eligible UG/professional students.','Driver/occupation proof, marksheet, income certificate, residence proof, admission/bonafide, ID and bank details.','Online through current scholarship route.','https://www.jktyre.com/','Guide states the 2026 deadline has already passed in the published cycle.'),
('p18','Virtusa Engineering Excellence Scholarship','private','Engineering-focused scholarship for eligible students from financially constrained backgrounds; course, academic and income criteria vary by annual notice.','Financial scholarship support plus possible development/mentoring components; confirm 2026–27 amount in current notice.','Marksheets, entrance/admission proof, income documents, ID, bank details and requested personal statement.','Current programme page/authorized scholarship platform.','https://www.virtusa.com/','Verify current notice.'),
('p19','Amazon Future Engineer Scholarship','private','Primarily female first-year engineering/computer-science students from low-income backgrounds; programme cycles use merit, financial need and selection criteria.','Published programme benefit: ₹2 lakh over four years plus technical training, mentorship and internship opportunities; current cohort terms should be checked.','Class XII/entrance/admission records, income proof, ID, bank details, essays/interview materials as requested.','Current Amazon Future Engineer/FFE programme route when cohort is open.','https://www.aboutamazon.in/news/community/amazon-future-engineer-scholarship-for-women-in-tech','Check current cohort terms.'),
('p20','Kotak Suraksha Scholarship','private','Eligible students under Kotak Education Foundation safety/education support initiatives; exact 2026–27 beneficiary conditions depend on active programme notice.','Financial educational support; amount and duration are programme-specific.','Marksheets, income/need documents, admission proof, ID, bank details and special-category documents if required.','Check current Kotak Education Foundation notice/application route.','https://www.kotakeducationfoundation.org/','Verify active programme notice.')
on conflict (id) do update set
name=excluded.name,type=excluded.type,eligibility=excluded.eligibility,benefits=excluded.benefits,
documents=excluded.documents,application_route=excluded.application_route,official_source=excluded.official_source,
status_notes=excluded.status_notes,updated_at=now();

insert into public.knowledge_documents
(title, source_file, source_type, language, content, verification_status)
select
'Scholarship Guide 2026–27 — Geetha Knowledge',
'scholarship_guide_2026_27.pdf',
'uploaded_document',
'en',
'Source-backed 2026–27 scholarship guidance supplied by the user and prepared/checked 30 September 2026. The guide covers 40 entries: 20 government and 20 private/CSR scholarships. It says the live official portal or annual notification is the final authority. NSP 2026–27 opened 1 June 2026; OTR is mandatory and is a unique 14-digit number for the student academic career. The NSP notice says students may apply for one merit-based scholarship scheme and one or more welfare-based scholarship schemes, subject to scheme rules. The guide states many NSP 2026–27 student deadlines are 31 October 2026, with scheme-specific exceptions; institute/department verification commonly follows in November. Tamil Nadu BC/MBC/DNC post-matric applications are routed through UMIS for the notified period; the guide states 18 September–21 October 2026 through the college nodal officer. Common documents include photo, accepted government ID/masked Aadhaar, Class 10/12 and previous marksheets, admission/bonafide, fee receipt/fee structure, income certificate, community/caste certificate where relevant, domicile where relevant, UDID/disability certificate where relevant, service/worker/martyr/dependency proof where relevant, bank passbook/cancelled cheque, entrance rank proof where required, death certificate where applicable, and declarations/affidavits. General workflow: identify exact scheme and eligibility; complete OTR/identity steps where required; fill matching certificate/bank details; upload readable documents; submit before deadline; complete institute/nodal verification; track status and DBT/payment on the official portal. Common rejection causes in the guide are wrong income/category details, name/DOB mismatch, unverified institute application, incorrect bank details, missing certificate, ineligible course/institution, or missed deadline.',
'source_document'
where not exists (
  select 1 from public.knowledge_documents
  where title='Scholarship Guide 2026–27 — Geetha Knowledge'
);


-- Geetha training dataset: curated bilingual examples used as free retrieval-based training data.
create table if not exists public.geetha_training_examples (
  id uuid primary key default gen_random_uuid(),
  category text not null,
  language text not null check (language in ('en','ta','mixed')),
  question text not null,
  answer text not null,
  source text,
  verification_status text not null default 'curated',
  created_at timestamptz not null default now()
);

alter table public.geetha_training_examples enable row level security;
drop policy if exists "Public can read Geetha training examples" on public.geetha_training_examples;
create policy "Public can read Geetha training examples" on public.geetha_training_examples for select using (true);

insert into public.geetha_training_examples (category,language,question,answer,source) values
('greeting','en','Hello Geetha','Hello! I am Geetha AI. I can help with scholarships, government schemes, TNEA, skills, jobs and application guidance.','SAMAM curated'),
('greeting','ta','வணக்கம் கீதா','வணக்கம்! நான் Geetha AI. உதவித்தொகை, அரசு திட்டங்கள், TNEA, திறன்கள், வேலை வாய்ப்புகள் மற்றும் விண்ணப்ப வழிகாட்டுதலில் உதவ முடியும்.','SAMAM curated'),
('government_schemes','en','How can I find a government scheme?','Start with the official scheme name, check eligibility, use the official source, prepare the required documents, submit through the official portal and save the application reference number.','SAMAM curated'),
('government_schemes','ta','அரசு திட்டத்தை எப்படி கண்டுபிடிப்பது?','அதிகாரப்பூர்வ திட்டப் பெயரை கண்டறிந்து, தகுதியை சரிபார்த்து, அதிகாரப்பூர்வ portal-ஐ பயன்படுத்தி, தேவையான ஆவணங்களை தயார் செய்து, விண்ணப்ப reference number-ஐ சேமிக்கவும்.','SAMAM curated'),
('scholarships','en','How do I find scholarships?','Use SAMAM’s scholarship information to identify relevant schemes, then verify the current eligibility, deadline and application route on the official portal before applying.','SAMAM curated'),
('scholarships','ta','உதவித்தொகை எப்படி தேடுவது?','SAMAM-ன் உதவித்தொகை தகவல்களில் பொருத்தமான திட்டங்களைப் பார்க்கலாம். விண்ணப்பிக்கும் முன் தற்போதைய தகுதி, கடைசி தேதி மற்றும் விண்ணப்ப வழியை அதிகாரப்பூர்வ portal-ல் சரிபார்க்கவும்.','SAMAM curated'),
('eligibility','en','What documents are usually needed for a scholarship?','Common documents can include identity proof, marksheets, admission or bonafide proof, fee details, income/community certificates and bank details. Exact requirements depend on the scheme.','SAMAM curated'),
('eligibility','ta','உதவித்தொகைக்கு என்ன ஆவணங்கள் தேவை?','பொதுவாக அடையாளச் சான்று, மதிப்பெண் சான்றிதழ்கள், சேர்க்கை அல்லது bonafide சான்று, கட்டண விவரம், வருமானம்/சமூகச் சான்றிதழ்கள் மற்றும் வங்கி விவரங்கள் தேவைப்படலாம். சரியான பட்டியல் திட்டத்தைப் பொறுத்தது.','SAMAM curated'),
('application','en','How do I apply for a scheme?','Check eligibility, open the official portal, prepare documents, complete the form carefully, submit it, save the reference number and track the status on the official portal.','SAMAM curated'),
('application','ta','திட்டத்திற்கு எப்படி விண்ணப்பிப்பது?','தகுதியை சரிபார்த்து, அதிகாரப்பூர்வ portal-ஐ திறந்து, ஆவணங்களை தயார் செய்து, படிவத்தை கவனமாக நிரப்பி, சமர்ப்பித்த பின் reference number-ஐ சேமித்து status-ஐ அதிகாரப்பூர்வ portal-ல் பார்க்கவும்.','SAMAM curated'),
('tnea','en','What is the TNEA process?','The basic flow is registration, certificate verification, choice filling, allotment and reporting to the allotted college. Check the official TNEA portal for current dates and rules.','SAMAM curated'),
('tnea','ta','TNEA நடைமுறை என்ன?','அடிப்படை நடைமுறை பதிவு, சான்றிதழ் சரிபார்ப்பு, விருப்பத் தேர்வு, allotment மற்றும் ஒதுக்கப்பட்ட கல்லூரியில் சேருதல். தற்போதைய தேதிகள் மற்றும் விதிகளுக்கு அதிகாரப்பூர்வ TNEA portal-ஐ சரிபார்க்கவும்.','SAMAM curated'),
('skills','en','Where can I learn skills for free?','SAMAM can guide you toward free or low-cost learning options such as SWAYAM and NPTEL. Check the provider’s current course details before enrolling.','SAMAM curated'),
('skills','ta','இலவசமாக திறன்களை எங்கே கற்கலாம்?','SWAYAM மற்றும் NPTEL போன்ற இலவச அல்லது குறைந்த செலவு கற்றல் தளங்களை SAMAM மூலம் அறியலாம். சேர்வதற்கு முன் தற்போதைய course விவரங்களை provider-ன் தளத்தில் சரிபார்க்கவும்.','SAMAM curated'),
('jobs','en','Where can I find jobs or internships?','Use SAMAM’s Jobs and Careers sections to explore opportunities. Before applying, verify the organisation, role and application link from an official or trusted source.','SAMAM curated'),
('jobs','ta','வேலை அல்லது internship எங்கே தேடுவது?','SAMAM-ன் Jobs மற்றும் Careers பகுதிகளில் வாய்ப்புகளைப் பார்க்கலாம். விண்ணப்பிக்கும் முன் நிறுவனம், பணி மற்றும் application link-ஐ அதிகாரப்பூர்வ அல்லது நம்பகமான மூலத்தில் சரிபார்க்கவும்.','SAMAM curated'),
('low_data','en','How does low data mode work?','Low-data mode keeps Geetha’s guidance lightweight and relies on locally available information where possible. Live government updates and final submissions still require internet access.','SAMAM curated'),
('low_data','ta','குறைந்த data mode எப்படி வேலை செய்கிறது?','குறைந்த data mode Geetha வழிகாட்டுதலை எளிமையாக வைத்துக்கொண்டு, முடிந்தவரை உள்ளூர் தகவலைப் பயன்படுத்துகிறது. அரசு தளத்தின் live updates மற்றும் இறுதி submission-க்கு இணையம் தேவை.','SAMAM curated'),
('sdg10','en','What is SAMAM trying to solve?','SAMAM supports SDG 10 by making opportunity information and guidance easier to access across scholarships, education, skills, jobs and government services.','SAMAM curated'),
('sdg10','ta','SAMAM என்ன பிரச்சினையை தீர்க்கிறது?','உதவித்தொகை, கல்வி, திறன்கள், வேலை மற்றும் அரசு சேவைகள் பற்றிய தகவல் மற்றும் வழிகாட்டுதலை எளிதாக அணுக உதவுவதன் மூலம் SAMAM SDG 10-ஐ ஆதரிக்கிறது.','SAMAM curated')
 on conflict do nothing;
